name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-slim

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup neovim
      uses: rhysd/action-setup-vim@v1
      with:
        version: nightly
        neovim: true

    - name: Setup lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "luajit-openresty"

    - name: Setup dependencies
      shell: bash
      run: git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim

    - name: Setup dependencies
      shell: bash
      run: make test
